### ISSUE TITLE
Simplify update-servers.js

### ISSUE THREAD

**Issue by garrettec1** [RadicalZephyr/bitburner-scripts#21]
Remove target prompt.

Run startup after purchase 

Run Share ( I suggest only 5% - 10% ram per server due to diminishing returns. )

Add logging

(~ maybe)
~ Set spend to always be 100%?

**Comment by RadicalZephyr** [comment]
- Switched to command line flags for all options.
- Added option to run start.js. default is to not do so.
- Spend percent defaults to 100%
